version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: portfoliodb
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: portfolio123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      sh -c "python portfolio/manage.py migrate &&
             gunicorn portfolio.portfolio.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://portfolio:portfolio123@db:5432/portfoliodb
    depends_on:
      - db

volumes:
  postgres_data:
